### ISSUE TITLE
Implement standard review links and progress bar

### ISSUE THREAD

**Issue by ekressmiller** [mplp/docassemble-FeeWaiverRequest#12]
Before we test with wider team, I think we will want the [nav panel](https://docs.google.com/document/d/1gzNbt_S5k6hcKNxq-lFtQF0iEnm0h5K7vXv7ABrgQbc/edit#heading=h.otzf402o5fu5) and small screen review links to be functioning as expected.

Note: This interview is currently pulling from Brett's special framework branch, which I think is why the Review link for small screens is not appearing.  

I think the [progress bar](https://docs.google.com/document/d/1gzNbt_S5k6hcKNxq-lFtQF0iEnm0h5K7vXv7ABrgQbc/edit#heading=h.opu2drruhuz7) should also be turned on.

**Comment by normon66** [comment]
@ekressmiller - you are correct - I branched off of the framework (bh_framework_dev) prior to your review and nav panel enhancements. 

Unless something comes up to give pause or question to [PR#92](https://github.com/mplp/docassemble-mlhframework/pull/92), I think it will end up being easier to merge bh_framework_dev into the framework and then doing another quick round of testing with the whole can of beans.
