### ISSUE TITLE
Weird annotations when you "View" instructions/coversheet page

### ISSUE THREAD

**Issue by ekressmiller** [mplp/docassemble-FeeWaiverRequest#14]
When I download the coversheet, it looks normal. When I "view" it, it has these weird annotations:
![image](https://github.com/mplp/docassemble-FeeWaiverRequest/assets/110936328/40dbfcfa-a49d-4874-93de-ab4b4d9e64de)
![image](https://github.com/mplp/docassemble-FeeWaiverRequest/assets/110936328/51c53ba8-b412-4076-8123-a4b681df0f61)

**Comment by normon66** [comment]
@ekressmiller - I have a few questions on this (thanks in advance!):
1) What browser/device was this on?
2) Did the form open in the browser (such as when Chrome opens a pdf in a new tab), or was this in docassemble's preview window?
3) This did not happen in the Fee Waiver or PII forms at all?

**Comment by ekressmiller** [comment]
1. It was in Chrome on desktop.
2. It's when Chrome opens the browser in a new tab.  (This happens for me if I click the "View" button on the download page instead of the "Download" button.)
3. I didn't see anything like this on the other docs, but I don't think I checked systematically.

**Comment by ekressmiller** [comment]
But @normon66 I am maybe going to suggest we go with a word doc template for the cover sheet, so I'd hold off on troubleshooting this too much yet.

**Comment by normon66** [comment]
A word doc makes more sense anyway since it will better handle dynamic text and paragraph sizes, such as cover sheets that may include a link to the mlh.org instructions.

**Comment by normon66** [comment]
@ekressmiller - can you please retest this when you have a moment? I think that your overhaul of the framework covers sheet resolved this, but I want to make sure you aren't still seeing it before I close it. Thanks!

https://da-dev.mplp.org/start/fee_waiver

**Comment by ekressmiller** [comment]
yep confirmed they do not show up. Closing now!
