### ISSUE TITLE
Addendum header styling

### ISSUE THREAD

**Issue by ekressmiller** [mplp/docassemble-FeeWaiverRequest#15]
Could the addendum header be more like the LHI version with the header that looks more like the standard court forms?

**Comment by normon66** [comment]
This was just using docassemble's simple and built-in addendum. I'll dig around to see if there's a way to use a custom pdf/attachment as the addendum base file.

**Comment by ekressmiller** [comment]
I did kind of an in-between version for the simple motion addendum.  Not quite as fancy as the LHI fee waiver one but a bit closer to it, so you could look at that as a starting point.
