### ISSUE TITLE
Ability to change party assignment on review screen

### ISSUE THREAD

**Issue by ekressmiller** [mplp/docassemble-FeeWaiverRequest#16]
Can we allow someone to change which party they are on the review screen? I'd hate for somebody to get it wrong and then have to redo the whole tool.

(Bryce essentially figured this out for the motion tool, so it could be worth asking for his help.)

**Comment by normon66** [comment]
Fixed in commit 2f167ed30e8156ab17ef0fa80c6b936a0be91fda
