### ISSUE TITLE
MC97 and 97a logic

### ISSUE THREAD

**Issue by ekressmiller** [mplp/docassemble-FeeWaiverRequest#18]
I tried a circuit court "in the matter of" case (NOT two parties).

LHI produced BOTH MC 97 and 97a.
Docassemble produced ONLY MC 97a.

I think the logic of the Docassemble interview makes more sense to me, so I'm not sure if this is an error with the old tool or the new one.

**Comment by normon66** [comment]
@ekressmiller - good catch! That is indeed an error on the LHI program. 

MC 97a is to be used "...for a person who is a NOT a defendant, respondent, or decedent..." For an "in the matter of" case, this should indeed be the one and only PII form to use. 

Closing as this (the docassemble version) is functioning correctly.
