### ISSUE TITLE
ID Court type choice: 
User feedback: something
(`court_type_selection`)

### ISSUE THREAD

**Issue by MPLP-Docassemble** [mplp/docassemble-FeeWaiverRequest#2]
&nbsp; | &nbsp;
-------|------------------------------------
Question ID | `Court type choice`
Details | test fee waiver feedback form 1
Variable being sought | `court_type_selection`
Package version | `playground`
Filename | `docassemble.playground5FeeWaiverRequest:fee_waiver_request.yml`

**Comment by normon66** [comment]
Test issue created for custom tester feedback form
