### ISSUE TITLE
ID user role: 
User feedback: something
(`user_ask_role`)

### ISSUE THREAD

**Issue by MPLP-Docassemble** [mplp/docassemble-FeeWaiverRequest#39]
&nbsp; | &nbsp;
-------|------------------------------------
Question ID | `user role`
Details | The "How do I know?" on this page is below the answer choices. On other pages it goes below the question/prompt but above the answer choices. I think I like it above the answer choices more.
Variable being sought | `user_ask_role`
Package version | `0.3`
Filename | `docassemble.FeeWaiverRequest:data/questions/fee_waiver_request.yml`

**Comment by normon66** [comment]
BEFORE
   ![image](https://github.com/user-attachments/assets/2c33ff17-1f92-4ca1-87c1-1dc8d9ed8d22)

AFTER
   ![image](https://github.com/user-attachments/assets/c92d2cd9-e4fe-4f8e-b323-0e783174870c)
