### ISSUE TITLE
ID MDHHS case number: 
User feedback: language
(`pa_mdhhs_case_number`)

### ISSUE THREAD

**Issue by MPLP-Docassemble** [mplp/docassemble-FeeWaiverRequest#4]
&nbsp; | &nbsp;
-------|------------------------------------
Question ID | `MDHHS case number`
Details | fghgf
Variable being sought | `pa_mdhhs_case_number`
Package version | `playground`
Filename | `docassemble.playground5FeeWaiverRequest:fee_waiver_request.yml`

**Comment by normon66** [comment]
TEST issue for testing feedback form
