### ISSUE TITLE
ID Court type choice: 
User feedback: bug
(`court_type_selection`)

### ISSUE THREAD

**Issue by MPLP-Docassemble** [mplp/docassemble-FeeWaiverRequest#5]
&nbsp; | &nbsp;
-------|------------------------------------
Question ID | `Court type choice`
Details | dhg
Variable being sought | `court_type_selection`
Package version | `playground`
Filename | `docassemble.playground5FeeWaiverRequest:fee_waiver_request.yml`

**Comment by normon66** [comment]
TEST issue for testing feedback form
