### ISSUE TITLE
No content initially displays on review screen if you say no to public assistance

### ISSUE THREAD

**Issue by ekressmiller** [mplp/docassemble-FeeWaiverRequest#50]
![image](https://github.com/user-attachments/assets/4988786d-3574-4562-8576-4e08c1324e51)

I think what is happening is that even though you have this code block in the main interview:
```
---
depends on: pa_received
code: |
  if pa_received == False:
    pa_food_assistance_program = False
    pa_medicaid = False
    pa_family_independence_program = False
    pa_women_infants_children = False
    pa_state_disability = False
    pa_state_emergency_relief = False
    pa_refugee_assistance = False
    pa_supplemental_security = False
    pa_other = False
---
```
I think there's nothing triggering the block to actually run, so pa_food_assistance_program, etc., don't get defined, which means the review screen entry that contains them doesn't display.

So I think a fix would be to do something in the interview to run this block. Maybe calling one of them in the interview order?

[other facts from my runthrough in case you want to reproduce: probate court, no to public assistance, and no to legal assistance]

**Comment by normon66** [comment]
Fixed by splitting of the main 'do you receive PA?' question into its own Edit block.

![image](https://github.com/user-attachments/assets/c3fe4251-9b1d-4dd7-aeb2-23a077a61abd)
