### ISSUE TITLE
You can't edit the user's name if case_type is "Matter"

### ISSUE THREAD

**Issue by ekressmiller** [mplp/docassemble-FeeWaiverRequest#52]
I think this is important enough to fix. If someone had to do the detailed financial info, then realized they had a typo in their name or something, it would be very frustrating not to be able to edit it. 

[Just realizing the name doesn't even go on the form in this instance unless they're e-signing, which is wild to me. Given that reality, maybe a quick-ish fix would be to delay name collection until after we get case_type. Then if it's Matter, wait and only collect name at the end if they say they want to e-sign. That way, if there were a typo, they could very quickly and easily get back to fix it without losing other info.]

**Comment by normon66** [comment]
Simply added an accordion section that only has the name that only appears when a Matter-type case.

![image](https://github.com/user-attachments/assets/66042d41-47fd-4d55-b90c-7728d02c8f19)

**Comment by ekressmiller** [comment]
awesome thanks!
