### ISSUE TITLE
ID Court type choice: 
User feedback: something
(`court_type_selection`)

### ISSUE THREAD

**Issue by MPLP-Docassemble** [mplp/docassemble-FeeWaiverRequest#7]
&nbsp; | &nbsp;
-------|------------------------------------
Question ID | `Court type choice`
Details | ghhg
Variable being sought | `court_type_selection`
Package version | `playground`
Filename | `docassemble.playground5FeeWaiverRequest:fee_waiver_request.yml`

**Comment by normon66** [comment]
It appears this was created by accident, probably when testing github/feedback form integration.
